[package]
name = "mkcss"
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/exact-rs/mkcss"
description = "ğŸ“ Simple css creation utility."

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
colored = "2.0.4"
env_logger = "0.10.0"
inquire = "0.6.2"
log = "0.4.20"
macros-rs = "0.4.0"
regex = "1.9.5"
scraper = "0.17.1"
